import { Configuration } from '@/shared/api/gen'
import { BaseAPI } from '@/shared/api/gen/base'
import axios, { AxiosError, AxiosInstance, AxiosResponse, InternalAxiosRequestConfig } from 'axios'
import { InnerAxiosError } from './errors'
import { usePluginOptionsStorage } from '@/shared/data/pinia/plugin-options'
